services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carcass-app
    ports:
      - "5005:5000"  # Внешний порт 5005, внутренний 5000
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-marbling_db}
      POSTGRES_HOST: ${POSTGRES_HOST:-host.docker.internal}
      POSTGRES_PORT: ${POSTGRES_PORT:-4444}
      SERVER_PORT: ${SERVER_PORT:-5000}
      NODE_ENV: production
      # Не нужно задавать VITE_API_URL - будет использоваться относительный путь
    volumes:
      - ./public/images:/app/public/images
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: